# Generated by Django 5.1.5 on 2025-02-10 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('students_list', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('student_level', models.CharField(max_length=50)),
                ('activity_level', models.CharField(max_length=50)),
                ('learning_style', models.CharField(max_length=50)),
                ('multiple_intelligence', models.CharField(max_length=100)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('parent_info', models.TextField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='planner.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('grade_level', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('duration', models.DurationField()),
                ('date', models.DateField()),
                ('objectives', models.TextField()),
                ('integration', models.TextField(blank=True, null=True)),
                ('teaching_strategy', models.TextField()),
                ('description', models.TextField()),
                ('activity_level', models.CharField(max_length=50)),
                ('activities', models.TextField()),
                ('assessment', models.TextField()),
                ('technology_used', models.TextField(blank=True, null=True)),
                ('plan_b', models.TextField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='planner.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='planner.user')),
            ],
        ),
    ]
